global:
  email-reply-to: dpxtools@salesforce.com
  notifications:
    on_production_branches_only: true
  preprocessor-tag: jenkins-sfci-sfci-managed-preprocessor-PR-6322-latest-itest

stages:
  build:
    - npm-setup:
        yarn-modern: true
    - step:
        name: yarn-build
        image: docker.repo.local.sfdc.net/sfci/docker-images/sfdc_rhel9_nodejs20/sfdc_rhel9_nodejs20_build:latest
        commands:
          - yarn install
          - yarn build
  integration-test:
    - downstream-dependency:
        downstream-repos:
          - repo-url: https://git.soma.salesforce.com/dpxtools/sfci-downstream-testing-gitsoma-repo1
            branches:
              - my-patch-branch
              - test-branch
          - repo-url: https://git.soma.salesforce.com/dpxtools/sfci-downstream-testing-gitsoma-repo2
            branches:
              - github-default
        packages-to-test:
          npm:
            - "o11y-sample-client"
            - "o11y-sample-node-server"

